name: Ci/Cd build

on:
  push:
    branches: [ "master" ]
 
jobs:
  build:
  
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn --version
      
  install:
  
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Install nginx and start the service
      run: sudo apt install nginx -y
      run: sudo systemctl start nginx

    - name: get the content
      run: curl -i http://localhost:80
